# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'v1.ui'
#
# Created: Mon Mar 13 09:59:02 2017
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from conf_data import conf_data


try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def save_(self):
        conf = conf_data()
        conf.a0 = self.a0.text()
        conf.b0 = self.b0.text()
        conf.a1 = self.a1.text()
        conf.b1 = self.b1.text()
        conf.a2 = self.a2.text()
        conf.b2 = self.b2.text()
        conf.a3 = self.a3.text()
        conf.b3 = self.b3.text()
        conf.x0 = self.x0.text()
        conf.y0 = self.y0.text()
        conf.x1 = self.x1.text()
        conf.y1 = self.y1.text()
        conf.x2 = self.x2.text()
        conf.y2 = self.y2.text()
        conf.x3 = self.x3.text()
        conf.y3 = self.y3.text()
        conf.threshold = self.threshold.value()
        conf.save()

    def load_(self):
        conf = conf_data()
        conf.load()
        self.a0.setText(conf.a0)  
        self.b0.setText(conf.b0)  
        self.a1.setText(conf.a1)  
        self.b1.setText(conf.b1)  
        self.a2.setText(conf.a2)  
        self.b2.setText(conf.b2)  
        self.a3.setText(conf.a3)  
        self.b3.setText(conf.b3)  
        self.x0.setText(conf.x0)  
        self.y0.setText(conf.y0)  
        self.x1.setText(conf.x1)  
        self.y1.setText(conf.y1)  
        self.x2.setText(conf.x2)  
        self.y2.setText(conf.y2)  
        self.x3.setText(conf.x3)  
        self.y3.setText(conf.y3)    
        self.threshold.setValue(int(conf.threshold))
        
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(744, 695)
        self.video = QtGui.QLabel(Dialog)
        self.video.setGeometry(QtCore.QRect(0, 0, 741, 431))
        self.video.setObjectName(_fromUtf8("video"))
        self.x0 = QtGui.QLineEdit(Dialog)
        self.x0.setGeometry(QtCore.QRect(30, 470, 113, 20))
        self.x0.setObjectName(_fromUtf8("x0"))
        self.y0 = QtGui.QLineEdit(Dialog)
        self.y0.setGeometry(QtCore.QRect(190, 470, 113, 20))
        self.y0.setObjectName(_fromUtf8("y0"))
        self.a0 = QtGui.QLineEdit(Dialog)
        self.a0.setGeometry(QtCore.QRect(420, 470, 113, 20))
        self.a0.setObjectName(_fromUtf8("a0"))
        self.b0 = QtGui.QLineEdit(Dialog)
        self.b0.setGeometry(QtCore.QRect(610, 470, 113, 20))
        self.b0.setObjectName(_fromUtf8("b0"))
        self.x1 = QtGui.QLineEdit(Dialog)
        self.x1.setGeometry(QtCore.QRect(30, 500, 113, 20))
        self.x1.setObjectName(_fromUtf8("x1"))
        self.x2 = QtGui.QLineEdit(Dialog)
        self.x2.setGeometry(QtCore.QRect(30, 530, 113, 20))
        self.x2.setObjectName(_fromUtf8("x2"))
        self.x3 = QtGui.QLineEdit(Dialog)
        self.x3.setGeometry(QtCore.QRect(30, 560, 113, 20))
        self.x3.setObjectName(_fromUtf8("x3"))
        self.y1 = QtGui.QLineEdit(Dialog)
        self.y1.setGeometry(QtCore.QRect(190, 500, 113, 20))
        self.y1.setObjectName(_fromUtf8("y1"))
        self.y2 = QtGui.QLineEdit(Dialog)
        self.y2.setGeometry(QtCore.QRect(190, 530, 113, 20))
        self.y2.setObjectName(_fromUtf8("y2"))
        self.y3 = QtGui.QLineEdit(Dialog)
        self.y3.setGeometry(QtCore.QRect(190, 560, 113, 20))
        self.y3.setObjectName(_fromUtf8("y3"))
        self.a1 = QtGui.QLineEdit(Dialog)
        self.a1.setGeometry(QtCore.QRect(420, 500, 113, 20))
        self.a1.setObjectName(_fromUtf8("a1"))
        self.a2 = QtGui.QLineEdit(Dialog)
        self.a2.setGeometry(QtCore.QRect(420, 530, 113, 20))
        self.a2.setObjectName(_fromUtf8("a2"))
        self.a3 = QtGui.QLineEdit(Dialog)
        self.a3.setGeometry(QtCore.QRect(420, 560, 113, 20))
        self.a3.setObjectName(_fromUtf8("a3"))
        self.b1 = QtGui.QLineEdit(Dialog)
        self.b1.setGeometry(QtCore.QRect(610, 500, 113, 20))
        self.b1.setObjectName(_fromUtf8("b1"))
        self.b2 = QtGui.QLineEdit(Dialog)
        self.b2.setGeometry(QtCore.QRect(610, 530, 113, 20))
        self.b2.setObjectName(_fromUtf8("b2"))
        self.b3 = QtGui.QLineEdit(Dialog)
        self.b3.setGeometry(QtCore.QRect(610, 560, 113, 20))
        self.b3.setObjectName(_fromUtf8("b3"))
        self.thresholdNumber = QtGui.QLCDNumber(Dialog)
        self.thresholdNumber.setGeometry(QtCore.QRect(30, 630, 64, 23))
        self.thresholdNumber.setObjectName(_fromUtf8("thresholdNumber"))
        self.threshold = QtGui.QSlider(Dialog)
        self.threshold.setGeometry(QtCore.QRect(30, 660, 291, 19))
        self.threshold.setOrientation(QtCore.Qt.Horizontal)
        self.threshold.setObjectName(_fromUtf8("threshold"))
        self.save_conf = QtGui.QPushButton(Dialog)
        self.save_conf.setGeometry(QtCore.QRect(530, 650, 75, 23))
        self.save_conf.setObjectName(_fromUtf8("save_conf"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(130, 640, 54, 12))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 470, 12, 12))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(160, 470, 12, 12))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 500, 16, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(160, 500, 12, 12))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 530, 12, 12))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(160, 530, 12, 12))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(10, 560, 12, 12))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(160, 560, 12, 12))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(390, 470, 16, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(390, 500, 12, 12))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(390, 530, 12, 12))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(390, 560, 12, 12))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(580, 470, 12, 12))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(580, 500, 12, 12))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(580, 530, 12, 12))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(580, 560, 12, 12))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.load_()
        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.threshold, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.thresholdNumber.display)
        QtCore.QObject.connect(self.save_conf, QtCore.SIGNAL(_fromUtf8("clicked()")),  self.save_)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.video.setText(_translate("Dialog", "video", None))
        self.save_conf.setText(_translate("Dialog", "保存配置", None))
        self.label.setText(_translate("Dialog", "灵敏度", None))
        self.label_2.setText(_translate("Dialog", "x0", None))
        self.label_3.setText(_translate("Dialog", "y0", None))
        self.label_4.setText(_translate("Dialog", "x1", None))
        self.label_5.setText(_translate("Dialog", "y1", None))
        self.label_6.setText(_translate("Dialog", "x2", None))
        self.label_7.setText(_translate("Dialog", "y2", None))
        self.label_8.setText(_translate("Dialog", "x3", None))
        self.label_9.setText(_translate("Dialog", "y3", None))
        self.label_10.setText(_translate("Dialog", "a0", None))
        self.label_11.setText(_translate("Dialog", "a1", None))
        self.label_12.setText(_translate("Dialog", "a2", None))
        self.label_13.setText(_translate("Dialog", "a3", None))
        self.label_14.setText(_translate("Dialog", "b0", None))
        self.label_15.setText(_translate("Dialog", "b1", None))
        self.label_16.setText(_translate("Dialog", "b2", None))
        self.label_17.setText(_translate("Dialog", "b3", None))


if __name__ == "__main__":
    import sys 
    import camera
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog) 
    Dialog.show()
    sys.exit(app.exec_())

