# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'v1.ui'
#
# Created: Mon Mar 13 13:40:17 2017
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def save_(self):
        conf = conf_data()
        conf.a0 = self.a0.text()
        conf.b0 = self.b0.text()
        conf.a1 = self.a1.text()
        conf.b1 = self.b1.text()
        conf.a2 = self.a2.text()
        conf.b2 = self.b2.text()
        conf.a3 = self.a3.text()
        conf.b3 = self.b3.text()
        conf.x0 = self.x0.text()
        conf.y0 = self.y0.text()
        conf.x1 = self.x1.text()
        conf.y1 = self.y1.text()
        conf.x2 = self.x2.text()
        conf.y2 = self.y2.text()
        conf.x3 = self.x3.text()
        conf.y3 = self.y3.text()
        conf.threshold = self.threshold.value()
        conf.save()

    def load_(self):
        conf = conf_data()
        conf.load()
        self.a0.setText(conf.a0)  
        self.b0.setText(conf.b0)  
        self.a1.setText(conf.a1)  
        self.b1.setText(conf.b1)  
        self.a2.setText(conf.a2)  
        self.b2.setText(conf.b2)  
        self.a3.setText(conf.a3)  
        self.b3.setText(conf.b3)  
        self.x0.setText(conf.x0)  
        self.y0.setText(conf.y0)  
        self.x1.setText(conf.x1)  
        self.y1.setText(conf.y1)  
        self.x2.setText(conf.x2)  
        self.y2.setText(conf.y2)  
        self.x3.setText(conf.x3)  
        self.y3.setText(conf.y3)    
        self.threshold.setValue(int(conf.threshold))
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(706, 216)
        self.widget = QtGui.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(50, 20, 624, 154))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.x0 = QtGui.QLineEdit(self.widget)
        self.x0.setObjectName(_fromUtf8("x0"))
        self.gridLayout.addWidget(self.x0, 0, 1, 1, 2)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.y0 = QtGui.QLineEdit(self.widget)
        self.y0.setObjectName(_fromUtf8("y0"))
        self.gridLayout.addWidget(self.y0, 0, 4, 1, 1)
        self.label_10 = QtGui.QLabel(self.widget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 0, 5, 1, 1)
        self.a0 = QtGui.QLineEdit(self.widget)
        self.a0.setObjectName(_fromUtf8("a0"))
        self.gridLayout.addWidget(self.a0, 0, 6, 1, 1)
        self.label_14 = QtGui.QLabel(self.widget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 0, 7, 1, 1)
        self.b0 = QtGui.QLineEdit(self.widget)
        self.b0.setObjectName(_fromUtf8("b0"))
        self.gridLayout.addWidget(self.b0, 0, 8, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.x1 = QtGui.QLineEdit(self.widget)
        self.x1.setObjectName(_fromUtf8("x1"))
        self.gridLayout.addWidget(self.x1, 1, 1, 1, 2)
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 1, 3, 1, 1)
        self.y1 = QtGui.QLineEdit(self.widget)
        self.y1.setObjectName(_fromUtf8("y1"))
        self.gridLayout.addWidget(self.y1, 1, 4, 1, 1)
        self.label_11 = QtGui.QLabel(self.widget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 1, 5, 1, 1)
        self.a1 = QtGui.QLineEdit(self.widget)
        self.a1.setObjectName(_fromUtf8("a1"))
        self.gridLayout.addWidget(self.a1, 1, 6, 1, 1)
        self.label_15 = QtGui.QLabel(self.widget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 1, 7, 1, 1)
        self.b1 = QtGui.QLineEdit(self.widget)
        self.b1.setObjectName(_fromUtf8("b1"))
        self.gridLayout.addWidget(self.b1, 1, 8, 1, 1)
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.x2 = QtGui.QLineEdit(self.widget)
        self.x2.setObjectName(_fromUtf8("x2"))
        self.gridLayout.addWidget(self.x2, 2, 1, 1, 2)
        self.label_7 = QtGui.QLabel(self.widget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 2, 3, 1, 1)
        self.y2 = QtGui.QLineEdit(self.widget)
        self.y2.setObjectName(_fromUtf8("y2"))
        self.gridLayout.addWidget(self.y2, 2, 4, 1, 1)
        self.label_12 = QtGui.QLabel(self.widget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 2, 5, 1, 1)
        self.a2 = QtGui.QLineEdit(self.widget)
        self.a2.setObjectName(_fromUtf8("a2"))
        self.gridLayout.addWidget(self.a2, 2, 6, 1, 1)
        self.label_16 = QtGui.QLabel(self.widget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 2, 7, 1, 1)
        self.b2 = QtGui.QLineEdit(self.widget)
        self.b2.setObjectName(_fromUtf8("b2"))
        self.gridLayout.addWidget(self.b2, 2, 8, 1, 1)
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.x3 = QtGui.QLineEdit(self.widget)
        self.x3.setObjectName(_fromUtf8("x3"))
        self.gridLayout.addWidget(self.x3, 3, 1, 1, 2)
        self.label_9 = QtGui.QLabel(self.widget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 3, 3, 1, 1)
        self.y3 = QtGui.QLineEdit(self.widget)
        self.y3.setObjectName(_fromUtf8("y3"))
        self.gridLayout.addWidget(self.y3, 3, 4, 1, 1)
        self.label_13 = QtGui.QLabel(self.widget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 3, 5, 1, 1)
        self.a3 = QtGui.QLineEdit(self.widget)
        self.a3.setObjectName(_fromUtf8("a3"))
        self.gridLayout.addWidget(self.a3, 3, 6, 1, 1)
        self.label_17 = QtGui.QLabel(self.widget)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 3, 7, 1, 1)
        self.b3 = QtGui.QLineEdit(self.widget)
        self.b3.setObjectName(_fromUtf8("b3"))
        self.gridLayout.addWidget(self.b3, 3, 8, 1, 1)
        self.thresholdNumber = QtGui.QLCDNumber(self.widget)
        self.thresholdNumber.setObjectName(_fromUtf8("thresholdNumber"))
        self.gridLayout.addWidget(self.thresholdNumber, 4, 1, 1, 1)
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 4, 2, 1, 2)
        self.save_conf = QtGui.QPushButton(self.widget)
        self.save_conf.setObjectName(_fromUtf8("save_conf"))
        self.gridLayout.addWidget(self.save_conf, 4, 6, 2, 2)
        self.threshold = QtGui.QSlider(self.widget)
        self.threshold.setOrientation(QtCore.Qt.Horizontal)
        self.threshold.setObjectName(_fromUtf8("threshold"))
        self.gridLayout.addWidget(self.threshold, 5, 1, 1, 4)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.threshold, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.thresholdNumber.display)
        QtCore.QObject.connect(self.save_conf, QtCore.SIGNAL(_fromUtf8("clicked()")),  self.save_)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label_2.setText(_translate("Dialog", "x0", None))
        self.label_3.setText(_translate("Dialog", "y0", None))
        self.label_10.setText(_translate("Dialog", "a0", None))
        self.label_14.setText(_translate("Dialog", "b0", None))
        self.label_4.setText(_translate("Dialog", "x1", None))
        self.label_5.setText(_translate("Dialog", "y1", None))
        self.label_11.setText(_translate("Dialog", "a1", None))
        self.label_15.setText(_translate("Dialog", "b1", None))
        self.label_6.setText(_translate("Dialog", "x2", None))
        self.label_7.setText(_translate("Dialog", "y2", None))
        self.label_12.setText(_translate("Dialog", "a2", None))
        self.label_16.setText(_translate("Dialog", "b2", None))
        self.label_8.setText(_translate("Dialog", "x3", None))
        self.label_9.setText(_translate("Dialog", "y3", None))
        self.label_13.setText(_translate("Dialog", "a3", None))
        self.label_17.setText(_translate("Dialog", "b3", None))
        self.label.setText(_translate("Dialog", "灵敏度", None))
        self.save_conf.setText(_translate("Dialog", "保存配置", None))


if __name__ == "__main__":
    import sys 
    import camera
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog) 
    Dialog.show()
    sys.exit(app.exec_())

